from django.conf import settings

FACEBOOK_APPLICATION_ID = getattr(settings, 'FACEBOOK_APPLICATION_ID')
FACEBOOK_APPLICATION_SECRET_KEY = getattr(settings, 'FACEBOOK_APPLICATION_SECRET_KEY')
FACEBOOK_APPLICATION_URL = getattr(settings, 'FACEBOOK_APPLICATION_URL')
FACEBOOK_APPLICATION_INITIAL_PERMISSIONS = getattr(settings, 'FACEBOOK_APPLICATION_INITIAL_PERMISSIONS', [])
DISABLED_PATHS = getattr(settings, 'DJANGOBOOK_DISABLED_PATHS', [])
ENABLED_PATHS = getattr(settings, 'DJANGOBOOK_ENABLED_PATHS', [])
